<h1>Assignment 1 of CSCI 6515</h1>

<p>
    [1] Your First task is to do the same research and nd reasonable re-
sources for such data and understand their format.<BR>
[2] You pre-process the data, Table 1, Table 2, and the resources you have
found. In this step, you do descriptive analysis for your data to understand
data better. This step creates a dataset for you to work on.<BR>
1
[3] Select some features that you want to work with them from all col-
lected data. Give a reasoning why did you choose these features?<BR>
[4]Answer the following questions:
1. What is the most important factor for his headache? Why? <BR>
2. Create a model to predict when will he get a headache between (Sep
1, 2020 - Dec 30, 2020) and what is the probability of his headache.<BR>
3. For days that the probability of headache is more than 70%, suggest
a signicant action to decrease the headache's probability. Explain
your method
    </p>

<h2>Importing Libraries:</h2>

In [471]:
####import necessary libraries
import warnings
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score
from sklearn.preprocessing import StandardScaler
from imblearn.under_sampling import NearMiss
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from scipy.stats import randint
from sklearn.tree import DecisionTreeClassifier

In [472]:
#Ignore warnings
warnings.filterwarnings('ignore')

In [473]:
#detect current dir, optional if the csv is not in current dir
os.getcwd()

'/Users/j/Desktop/ML-BigData'

<h2>Data Collection:</h2>
<p> 1. We have obtained the weather data from <i><b><a href="https://climate.weather.gc.ca/">https://climate.weather.gc.ca/</a></b></i> for the year 2019 between September 1st to December 31st from 5 different weather stations in Halifax<p>
<p> 2. The dataset for regular work, headache and workout schedule was obtained from the assignment handouts</p>

In [474]:
#Read the source data (hourly data)

#Sept
df_2019_sep_STANFIELD_1 = pd.read_csv('STANFIELD_1_en_climate_hourly_NS_8202251_09-2019_P1H.csv', sep=',')
df_2019_sep_STANFIELD_2 = pd.read_csv('STANFIELD_2_en_climate_hourly_NS_8202249_09-2019_P1H.csv', sep=',')
df_2019_sep_KOOTENAY = pd.read_csv('KOOTENAY_en_climate_hourly_NS_8202252_09-2019_P1H.csv', sep=',')
df_2019_sep_DOCKYARD = pd.read_csv('HALIFAX_DOCKYARD_en_climate_hourly_NS_8202240_09-2019_P1H.csv', sep=',')
df_2019_sep_WINDSOR = pd.read_csv('WINDSOR_en_climate_hourly_NS_8202255_09-2019_P1H.csv', sep=',')

#Oct
df_2019_oct_STANFIELD_1 = pd.read_csv('STANFIELD_1_en_climate_hourly_NS_8202251_10-2019_P1H.csv', sep=',')
df_2019_oct_STANFIELD_2 = pd.read_csv('STANFIELD_2_en_climate_hourly_NS_8202249_10-2019_P1H.csv', sep=',')
df_2019_oct_KOOTENAY = pd.read_csv('KOOTENAY_en_climate_hourly_NS_8202252_10-2019_P1H.csv', sep=',')
df_2019_oct_DOCKYARD = pd.read_csv('HALIFAX_DOCKYARD_en_climate_hourly_NS_8202240_10-2019_P1H.csv', sep=',')
df_2019_oct_WINDSOR = pd.read_csv('WINDSOR_en_climate_hourly_NS_8202255_10-2019_P1H.csv', sep=',')

#Nov
df_2019_nov_STANFIELD_1 = pd.read_csv('STANFIELD_1_en_climate_hourly_NS_8202251_11-2019_P1H.csv', sep=',')
df_2019_nov_STANFIELD_2 = pd.read_csv('STANFIELD_2_en_climate_hourly_NS_8202249_11-2019_P1H.csv', sep=',')
df_2019_nov_KOOTENAY = pd.read_csv('KOOTENAY_en_climate_hourly_NS_8202252_11-2019_P1H.csv', sep=',')
df_2019_nov_DOCKYARD = pd.read_csv('HALIFAX_DOCKYARD_en_climate_hourly_NS_8202240_11-2019_P1H.csv', sep=',')
df_2019_nov_WINDSOR = pd.read_csv('WINDSOR_en_climate_hourly_NS_8202255_11-2019_P1H.csv', sep=',')

#Dec
df_2019_dec_STANFIELD_1 = pd.read_csv('STANFIELD_1_en_climate_hourly_NS_8202251_12-2019_P1H.csv', sep=',')
df_2019_dec_STANFIELD_2 = pd.read_csv('STANFIELD_2_en_climate_hourly_NS_8202249_12-2019_P1H.csv', sep=',')
df_2019_dec_KOOTENAY = pd.read_csv('KOOTENAY_en_climate_hourly_NS_8202252_12-2019_P1H.csv', sep=',')
df_2019_dec_DOCKYARD = pd.read_csv('HALIFAX_DOCKYARD_en_climate_hourly_NS_8202240_12-2019_P1H.csv', sep=',')
df_2019_dec_WINDSOR = pd.read_csv('WINDSOR_en_climate_hourly_NS_8202255_12-2019_P1H.csv', sep=',')


# Reading regular work data along with headache values
df_headache = pd.read_csv('table1_journal_headache.csv', sep=',')

# Reading workout data
df_workout = pd.read_csv('table2_workout.csv', sep=',')

<h2>Analysing the Data:</h2>
<h4>W.R.T one station</h4>
<p> 1. Displaying sample records of the data</p>
<p> 2. Checking the shape of the data</p>
<p> 3. Displaying the column names</p>
<p> 4. Describing the data obtained by calculating its standard deviation, mean, counts, etc.</p>
<p> 4. Checking for NULL values</p>

In [475]:
#displaying one sample file - weather data
df_2019_sep_STANFIELD_1.head(5)

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Time,Temp (Â°C),...,Wind Spd Flag,Visibility (km),Visibility Flag,Stn Press (kPa),Stn Press Flag,Hmdx,Hmdx Flag,Wind Chill,Wind Chill Flag,Weather
0,-63.51,44.88,HALIFAX STANFIELD INT'L A,8202251,2019-09-01 00:00,2019,9,1,00:00,15.6,...,NaN,24.1,NaN,100.44,NaN,NaN,NaN,NaN,NaN,NaN
1,-63.51,44.88,HALIFAX STANFIELD INT'L A,8202251,2019-09-01 01:00,2019,9,1,01:00,15.5,...,NaN,24.1,NaN,100.49,NaN,NaN,NaN,NaN,NaN,NaN
2,-63.51,44.88,HALIFAX STANFIELD INT'L A,8202251,2019-09-01 02:00,2019,9,1,02:00,15.3,...,NaN,24.1,NaN,100.56,NaN,NaN,NaN,NaN,NaN,Mostly Cloudy
3,-63.51,44.88,HALIFAX STANFIELD INT'L A,8202251,2019-09-01 03:00,2019,9,1,03:00,13.9,...,NaN,24.1,NaN,100.61,NaN,NaN,NaN,NaN,NaN,NaN
4,-63.51,44.88,HALIFAX STANFIELD INT'L A,8202251,2019-09-01 04:00,2019,9,1,04:00,12.6,...,NaN,24.1,NaN,100.64,NaN,NaN,NaN,NaN,NaN,NaN

In [476]:
#Shape of one file - weather data
df_2019_dec_STANFIELD_1.shape

(744, 28)

In [477]:
#displaying the column names of one file - weather data
df_2019_dec_STANFIELD_1.columns

Index(['Longitude (x)', 'Latitude (y)', 'Station Name', 'Climate ID',
       'Date/Time', 'Year', 'Month', 'Day', 'Time', 'Temp (Â°C)', 'Temp Flag',
       'Dew Point Temp (Â°C)', 'Dew Point Temp Flag', 'Rel Hum (%)',
       'Rel Hum Flag', 'Wind Dir (10s deg)', 'Wind Dir Flag',
       'Wind Spd (km/h)', 'Wind Spd Flag', 'Visibility (km)',
       'Visibility Flag', 'Stn Press (kPa)', 'Stn Press Flag', 'Hmdx',
       'Hmdx Flag', 'Wind Chill', 'Wind Chill Flag', 'Weather'],
      dtype='object')

In [478]:
#displaying the data with values and also their standard deviation,mean,count,etc - weather data
df_2019_dec_STANFIELD_1.describe()

,Longitude (x),Latitude (y),Climate ID,Year,Month,Day,Temp (Â°C),Temp Flag,Dew Point Temp (Â°C),Dew Point Temp Flag,...,Wind Spd (km/h),Wind Spd Flag,Visibility (km),Visibility Flag,Stn Press (kPa),Stn Press Flag,Hmdx,Hmdx Flag,Wind Chill,Wind Chill Flag
count,7.440000e+02,7.440000e+02,744.0,744.0,744.0,744.000000,744.000000,0.0,744.000000,0.0,...,744.000000,0.0,744.000000,0.0,744.000000,0.0,0.0,0.0,521.000000,0.0
mean,-6.351000e+01,4.488000e+01,8202251.0,2019.0,12.0,16.000000,-1.717742,NaN,-4.170565,NaN,...,21.102151,NaN,19.520833,NaN,99.575296,NaN,NaN,NaN,-10.057582,NaN
std,1.422041e-13,2.701879e-13,0.0,0.0,0.0,8.950289,5.200619,NaN,6.277262,NaN,...,10.534583,NaN,8.086205,NaN,1.205804,NaN,NaN,NaN,3.740185,NaN
min,-6.351000e+01,4.488000e+01,8202251.0,2019.0,12.0,1.000000,-11.300000,NaN,-15.800000,NaN,...,1.000000,NaN,0.200000,NaN,96.340000,NaN,NaN,NaN,-21.000000,NaN
25%,-6.351000e+01,4.488000e+01,8202251.0,2019.0,12.0,8.000000,-5.200000,NaN,-8.800000,NaN,...,13.000000,NaN,19.300000,NaN,98.840000,NaN,NaN,NaN,-12.000000,NaN
50%,-6.351000e+01,4.488000e+01,8202251.0,2019.0,12.0,16.000000,-2.050000,NaN,-5.100000,NaN,...,20.000000,NaN,24.100000,NaN,99.600000,NaN,NaN,NaN,-10.000000,NaN
75%,-6.351000e+01,4.488000e+01,8202251.0,2019.0,12.0,24.000000,0.525000,NaN,-0.375000,NaN,...,28.000000,NaN,24.100000,NaN,100.430000,NaN,NaN,NaN,-7.000000,NaN
max,-6.351000e+01,4.488000e+01,8202251.0,2019.0,12.0,31.000000,14.100000,NaN,13.900000,NaN,...,62.000000,NaN,32.200000,NaN,102.220000,NaN,NaN,NaN,-2.000000,NaN

In [479]:
#check null fields - weather data
df_2019_sep_WINDSOR.isnull().sum()

Longitude (x)            0
Latitude (y)             0
Station Name             0
Climate ID               0
Date/Time                0
Year                     0
Month                    0
Day                      0
Time                     0
Temp (Â°C)                0
Temp Flag              720
Dew Point Temp (Â°C)      0
Dew Point Temp Flag    720
Rel Hum (%)              0
Rel Hum Flag           720
Wind Dir (10s deg)      15
Wind Dir Flag          720
Wind Spd (km/h)          0
Wind Spd Flag          720
Visibility (km)        720
Visibility Flag        720
Stn Press (kPa)          0
Stn Press Flag         720
Hmdx                   675
Hmdx Flag              720
Wind Chill             720
Wind Chill Flag        720
Weather                720
dtype: int64

<h4> W.R.T regular work</h4>
<p> 1. Displaying sample records of the data</p>
<p> 4. Checking for NULL values</p>

In [480]:
#displaying regular work file
df_headache.head(5)

   Days  Month  Severity Working  Headache
0     1      9       NaN     Yes         0
1     2      9       NaN     Yes         0
2     3      9       NaN     Yes         0
3     4      9       NaN     Yes         0
4     5      9       0.8     Yes         1

In [481]:
#check null fields - regular work data with headache values
df_headache.isnull().sum()

Days          0
Month         0
Severity    112
Working       0
Headache      0
dtype: int64

<h4> W.R.T workout</h4>
<p> 1. Displaying sample records of the data</p>
<p> 4. Checking for NULL values</p>

In [482]:
#displaying workout file
df_workout.head(5)

   Days  Month Exercise
0     1      9       No
1     2      9      Yes
2     3      9       No
3     4      9      Yes
4     5      9       No

In [483]:
#check null fields - workout data
df_workout.isnull().sum()

Days        0
Month       0
Exercise    0
dtype: int64

<h2>Data Pre-processing:</h2>
<h4>W.R.T Weather Data</h4>
<p> 1. Built and calling reusable function 1 for cleaning and processing the data such as index setting, removing unwanted column and replacing missing values</p>
<p> 2. Combining all 5 weather station files for a month into one file</p>
<p> 3. Built and calling reusable function 2 for cleaning and processing the data such as index resetting, removing unwanted column and grouping the data day-wise by taking their mean values</p>
<p> 4. Combining all 4 months files into one file as 2019 dataset</p>
<p> 5. Analyzing the final 2019 weather dataset</p>

In [484]:
#reusable preprocessing function1
#set index as Date/Time
#removing unnecessary features
#fill missing values with mean via SimpleImputer
from sklearn.impute import SimpleImputer
def preProcessing(df):
    df = df.set_index(pd.DatetimeIndex(df['Date/Time']))
    df = df.drop(['Temp Flag', 'Dew Point Temp Flag', 'Rel Hum Flag', 'Wind Dir Flag', 'Wind Spd Flag', 'Visibility Flag', 'Stn Press Flag', 'Hmdx Flag', 'Wind Chill Flag', 'Visibility (km)', 'Longitude (x)', 'Wind Dir (10s deg)', 'Latitude (y)', 'Stn Press (kPa)', 'Station Name', 'Climate ID', 'Weather','Hmdx','Wind Chill'], axis=1)
    imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
    imputer.fit(df.iloc[:, 5:10])
    df.iloc[:, 5:10] = imputer.transform(df.iloc[:, 5:10])
    return df

In [485]:
#Calling preprocessing function1

#dec
df_2019_dec_STANFIELD_1 = preProcessing(df_2019_dec_STANFIELD_1)
df_2019_dec_STANFIELD_2 = preProcessing(df_2019_dec_STANFIELD_2)
df_2019_dec_KOOTENAY = preProcessing(df_2019_dec_KOOTENAY)
df_2019_dec_DOCKYARD = preProcessing(df_2019_dec_DOCKYARD)
df_2019_dec_WINDSOR = preProcessing(df_2019_dec_WINDSOR)
#nov
df_2019_nov_STANFIELD_1 = preProcessing(df_2019_nov_STANFIELD_1)
df_2019_nov_STANFIELD_2 = preProcessing(df_2019_nov_STANFIELD_2)
df_2019_nov_KOOTENAY = preProcessing(df_2019_nov_KOOTENAY)
df_2019_nov_DOCKYARD = preProcessing(df_2019_nov_DOCKYARD)
df_2019_nov_WINDSOR = preProcessing(df_2019_nov_WINDSOR)
#oct
df_2019_oct_STANFIELD_1 = preProcessing(df_2019_oct_STANFIELD_1)
df_2019_oct_STANFIELD_2 = preProcessing(df_2019_oct_STANFIELD_2)
df_2019_oct_KOOTENAY = preProcessing(df_2019_oct_KOOTENAY)
df_2019_oct_DOCKYARD = preProcessing(df_2019_oct_DOCKYARD)
df_2019_oct_WINDSOR = preProcessing(df_2019_oct_WINDSOR)
#sep
df_2019_sep_STANFIELD_1 = preProcessing(df_2019_sep_STANFIELD_1)
df_2019_sep_STANFIELD_2 = preProcessing(df_2019_sep_STANFIELD_2)
df_2019_sep_KOOTENAY = preProcessing(df_2019_sep_KOOTENAY)
df_2019_sep_DOCKYARD = preProcessing(df_2019_sep_DOCKYARD)
df_2019_sep_WINDSOR = preProcessing(df_2019_sep_WINDSOR)

In [486]:
#Combining all the monthly station files (grouped by Date/Time 2019)

df_2019_dec = pd.concat([df_2019_dec_STANFIELD_1, df_2019_dec_STANFIELD_2, df_2019_dec_KOOTENAY, df_2019_dec_DOCKYARD, df_2019_dec_WINDSOR]).groupby(df_2019_dec_STANFIELD_1['Date/Time']).mean()
df_2019_nov = pd.concat([df_2019_nov_STANFIELD_1, df_2019_nov_STANFIELD_2, df_2019_nov_KOOTENAY, df_2019_nov_DOCKYARD, df_2019_nov_WINDSOR]).groupby(df_2019_nov_STANFIELD_1['Date/Time']).mean()
df_2019_sep = pd.concat([df_2019_sep_STANFIELD_1, df_2019_sep_STANFIELD_2, df_2019_sep_KOOTENAY, df_2019_sep_DOCKYARD, df_2019_sep_WINDSOR]).groupby(df_2019_sep_STANFIELD_1['Date/Time']).mean()
df_2019_oct = pd.concat([df_2019_oct_STANFIELD_1, df_2019_oct_STANFIELD_2, df_2019_oct_KOOTENAY, df_2019_oct_DOCKYARD, df_2019_oct_WINDSOR]).groupby(df_2019_oct_STANFIELD_1['Date/Time']).mean()

In [487]:
#reusable preprocessing function2
#reseting Date/Time index
#drop Date/Time and grouping day-wise by taking their mean

def preProcessing2(df):
    df = df.reset_index()
    df = df.drop(['Date/Time'], axis=1)
    df = df.groupby('Day').mean()
    return df

In [488]:
#Calling preprocessing function2
df_2019_dec = preProcessing2(df_2019_dec)
df_2019_sep = preProcessing2(df_2019_sep)
df_2019_nov = preProcessing2(df_2019_nov)
df_2019_oct = preProcessing2(df_2019_oct)

In [489]:
#Concatenating the four month data into one file
frames = [df_2019_sep, df_2019_oct, df_2019_nov, df_2019_dec]
df_2019_public_weather_datasets = pd.concat(frames)

In [490]:
#checking the final weather dataset
df_2019_public_weather_datasets.head(10)

     Year  Month  Temp (Â°C)  Dew Point Temp (Â°C)  Rel Hum (%)  Wind Spd (km/h)
Day
1    2019      9  16.656727             9.676526    65.560241        11.304016
2    2019      9  16.505894            13.624026    83.960241        13.079016
3    2019      9  18.277560            15.534859    84.810241         9.904016
4    2019      9  18.023394            15.489026    85.968574        12.920683
5    2019      9  18.115060            12.076526    70.085241        14.529016
6    2019      9  15.386727             9.750693    70.368574        10.529016
7    2019      9  14.125060            11.359026    84.151908        33.304016
8    2019      9  12.525894             6.344859    67.710241        22.895683
9    2019      9  14.417560             8.704859    70.793574        11.687349
10   2019      9  14.832560             9.734859    73.426908         8.870683

<h4>W.R.T regular work and headache data</h4>
<p> 1. Cleaning and processing the data such as replacing missing values (NaN's) with 0's, replacing string values into binary values, setting index as "Days"</p>
<p> 2. Analyzing the final 2019 regular work - headache dataset</p>

In [491]:
#Preprocessing regular work schedule with headache values.
df_headache['Severity'] = df_headache['Severity'].fillna(0)
df_headache['Working'] = df_headache['Working'].str.replace('Yes', '1')
df_headache['Working'] = df_headache['Working'].str.replace('No', '0')

# Setting Days as index for the dataframe
df_headache = df_headache.set_index('Days')

In [492]:
#checking headache dataset
df_headache.head()

      Month  Severity Working  Headache
Days
1         9       0.0       1         0
2         9       0.0       1         0
3         9       0.0       1         0
4         9       0.0       1         0
5         9       0.8       1         1

<h4>W.R.T workout data</h4>
<p> 1. Cleaning and processing the data such as replacing string values into binary values, setting index as "Days"</p>
<p> 2. Analyzing the final 2019 workout dataset</p>

In [493]:
#Preprocessing workout data
df_workout['Exercise'] = df_workout['Exercise'].str.replace('Yes', '1')
df_workout['Exercise'] = df_workout['Exercise'].str.replace('No', '0')
df_workout = df_workout.set_index('Days')
df_workout

      Month Exercise
Days
1         9        0
2         9        1
3         9        0
4         9        1
5         9        0
...     ...      ...
27       12        0
28       12        0
29       12        0
30       12        0
31       12        0

[122 rows x 2 columns]

<h4>Combining weather, workout and regular work - headache data to form the 2019 final dataset</h4>
<h4>Removing unwanted columns from the final 2019 dataset</h4>
<h4>rearranging the columns of final 2019 train dataset</h4>

In [494]:
#combining all the three dataframes by concatination
#removing month and year columns from the final train dataset
# Rearranging columns to put dependent variable at last
workout_work_dataset = pd.concat([df_workout, df_headache], axis=1, sort=False)
final_train_dataset = pd.concat([workout_work_dataset, df_2019_public_weather_datasets], axis=1, sort=False)
final_train_dataset = final_train_dataset.drop(['Month','Year',], axis=1)
final_train_dataset = final_train_dataset[[
 'Temp (Â°C)',
 'Dew Point Temp (Â°C)',
 'Rel Hum (%)',
 'Wind Spd (km/h)',
 'Working',
 'Exercise',
 'Headache']]
final_train_dataset

,Temp (Â°C),Dew Point Temp (Â°C),Rel Hum (%),Wind Spd (km/h),Working,Exercise,Headache
1,16.656727,9.676526,65.560241,11.304016,1,0,0
2,16.505894,13.624026,83.960241,13.079016,1,1,0
3,18.277560,15.534859,84.810241,9.904016,1,0,0
4,18.023394,15.489026,85.968574,12.920683,1,1,0
5,18.115060,12.076526,70.085241,14.529016,1,0,1
...,...,...,...,...,...,...,...
27,-3.605833,-6.414167,81.400000,11.675000,1,0,0
28,2.880000,0.170833,82.958333,19.116667,0,0,0
29,-0.766667,-6.770000,64.208333,17.741667,0,0,0
30,-2.716667,-6.858333,73.583333,16.925000,1,0,0
31,0.112500,-1.990000,86.133333,29.616667,1,0,0

<h4> W.R.T workout and regular work - headache data for the final prediction set</h4>
<h4> Combining weather, workout and regular work - headache data to form the final prediction set - september only</h4>
<h4>Removing unwanted columns from final prediction set - september only</h4>

In [495]:
#checking the prediction dataset which consist of (workout_work_dataset_test), selecting only september data.
#removing the month, headache and severity columns from the workout-work-headache prediciton datatset
workout_work_dataset_test = pd.concat([df_workout, df_headache], axis=1, sort=False)
workout_work_dataset_test = workout_work_dataset_test.iloc[:30,:]
workout_work_dataset_test = workout_work_dataset_test.drop(['Month','Severity','Headache'], axis=1)
workout_work_dataset_test

     Exercise Working
Days
1           0       1
2           1       1
3           0       1
4           1       1
5           0       1
6           1       1
7           0       0
8           0       0
9           0       1
10          0       1
11          0       1
12          0       1
13          0       1
14          0       1
15          0       0
16          0       0
17          0       1
18          0       1
19          0       1
20          0       1
21          0       1
22          0       1
23          0       0
24          0       0
25          0       1
26          0       1
27          1       1
28          0       1
29          0       1
30          0       1

<h2> Splitting the final 2019 dataset into features in X and the dependent variable in y (target variable)</h2>

In [496]:
#splitting the dataset i.e. dependent variable and independent variables
X = final_train_dataset.iloc[:, :6]
y = final_train_dataset.iloc[:, -1]

<h3>Splitting dataset into test set and train set:</h3>

In [497]:
# splitting the dataset into train and test with all selected features
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [498]:
# splitting the dataset into train and test with all selected features except workout and regular work schedule.
X_train_1 = X_train.iloc[:, :4]
X_test_1 = X_test.iloc[:, :4]

<h3>Feature Scaling:</h3>
<p>1. Standarizing all the features to a common scale (Temp, Dew Point Temp, Rel Hum, Wind Spd, Working, Exercise)</p> 
<p>2. Standarizing all the selected features to a common scale except workout and regular work features i.e. (Temp, Dew Point Temp, Rel Hum, Wind Spd)</p>

In [499]:
#Implementation of StandardScaler for the standardization of features
sc = StandardScaler()
X_train.iloc[:, :4] = sc.fit_transform(X_train.iloc[:, :4])
X_test.iloc[:, :4] = sc.transform(X_test.iloc[:, :4])
X_train_1 = sc.fit_transform(X_train_1)
X_test_1 = sc.transform(X_test_1)

<h3>Implementation of various Decision Tree models:</h3>
<h4>Decision Tree Model-1 (Temp, Dew Point Temp, Rel Hum, Wind Spd, Working, Exercise)</h4>
<p> 1. Training the model with all features</p>
<p> 2. Predict the values on the test dataset<p>
<p> 3. Analyzing the predicted output and its probability<p>
<p> 4. Checking for feature importance and their weights<p>
<p> 5. Analyzing the confusion matrix, accuracy scores, precision scores, recall scores and f1 scores <p>

In [500]:
#checking the predictions of the test dataset
#display the prediction result of model1
clf = DecisionTreeClassifier(random_state = 0)
tree_clf = clf.fit(X_train,y_train)
y_pred = tree_clf.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0])

In [501]:
#displaying the probability scores
y_pred_proba = tree_clf.predict_proba(X_test)
y_pred_proba

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [502]:
#find the important features of the final dataset and their scores
importances = tree_clf.feature_importances_
importances

array([0.46092113, 0.0979798 , 0.16840278, 0.23381543, 0.02551557,
       0.0133653 ])

In [503]:
#prediction accuracy, precision, recall and f1 scores for model1
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("f1 Score", f1_score(y_test, y_pred,average = "macro") )
print("Confusion matrix", confusion_matrix(y_test,y_pred))
print("precision Score", precision_score(y_test, y_pred))
print("recall Score", recall_score(y_test, y_pred))

Accuracy: 0.88
f1 Score 0.4680851063829787
Confusion matrix [[22  2]
 [ 1  0]]
precision Score 0.0
recall Score 0.0

<h4>Decision Tree Model-2 (Temp, Dew Point Temp, Rel Hum, Wind Spd)</h4>
<p>1. Training the model with all the selected features<p>
<p>2. Predict the values on the test dataset<p>
<p>3. Analyzing the predicted output and its probability<p>
<p> 4. Checking for feature importance and their weights<p>
<p> 5. Analyzing the confusion matrix, accuracy scores, precision scores, recall scores and f1 scores <p>

In [504]:
#checking the predictions of the test dataset
#display the prediction result of model2
clf1 = DecisionTreeClassifier(random_state = 0)
tree_clf1 = clf1.fit(X_train_1,y_train)
y_pred_1 = tree_clf1.predict(X_test_1)
y_pred_1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0])

In [505]:
#displaying the probability scores
y_pred_proba_1 = tree_clf1.predict_proba(X_test_1)
y_pred_proba_1

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [506]:
#find the important features of the final dataset and their scores
importances_1 = tree_clf1.feature_importances_
importances_1

array([0.43030244, 0.18983586, 0.12757786, 0.25228384])

In [507]:
#prediction accuracy, precision, recall and f1 scores for model2
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_1))
print("f1 Score", f1_score(y_test, y_pred_1,average = "macro") )
print("Confusion matrix", confusion_matrix(y_test,y_pred_1))
print("precision Score", precision_score(y_test, y_pred_1))
print("recall Score", recall_score(y_test, y_pred_1))

Accuracy: 0.84
f1 Score 0.45652173913043476
Confusion matrix [[21  3]
 [ 1  0]]
precision Score 0.0
recall Score 0.0

<h3>Hyper parameter tuning:</h3>
<p> 1. Performing hyperparameter tuning via GridSearchCV</p>
<p> 2. Analysing the obtained best parameters for our Decision Tree by validating their best scores</p>
<p> 3. After hyperparameter tuning, applying the best parameter values to our models to train</p>

In [508]:
#input range of values for hyperparameter tuning.
param = {"max_depth": range(1,30), "min_samples_leaf": range(1,30), "criterion": ["gini","entropy"]}

In [509]:
# implementation of DecisionTreeClassifier with GridSearchCV
clf2 = DecisionTreeClassifier(random_state = 0, class_weight = "balanced")
tree_clf2 = GridSearchCV(clf2, param_grid=param, cv=5)
tree_clf3 = GridSearchCV(clf2, param_grid=param, cv=5)

<h4>Decision Tree Model-1 (Temp, Dew Point Temp, Rel Hum, Wind Spd, Working, Exercise)</h4>
<p> 1. Fit the decision tree model to the dataset(X_train,y_train)<p>
<p> 2. Analyzing the best score and the parameter values<p>
<p> 3. Analyzing the predicted output and its probability (X_test)<p>
<p> 4. Analyzing the confusion matrix, accuracy scores, precision scores, recall scores and f1 scores <p>

In [510]:
#Fit the decision tree model with X_train and y_train
tree_clf2 = tree_clf2.fit(X_train,y_train)

In [511]:
#checking the best score for the model by applying those tuned parameters
#checking the best parameters value for the model after performing hyperparameter tuning
print(tree_clf2.best_score_)
print(tree_clf2.best_params_)

0.8352631578947367
{'criterion': 'gini', 'max_depth': 10, 'min_samples_leaf': 1}

In [512]:
#Applying the tuned parameter values on the Decision tree Model-1 (Temp, Dew Point Temp, Rel Hum, Wind Spd, Working, Exercise)
#prediction on X_test post hyper parameter tuning
y_pred_2 = tree_clf2.predict(X_test)
y_pred_2

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0])

In [515]:
#displaying the probability scores for decision tree Model-1 (Temp, Dew Point Temp, Rel Hum, Wind Spd, Working, Exercise)
y_pred_proba_2 = tree_clf2.predict_proba(X_test)
y_pred_proba_2

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [516]:
#prediction accuracy, precision, recall and f1 scores for model1
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_2))
print("f1 Score", f1_score(y_test, y_pred_2,average = "macro") )
print("Confusion matrix", confusion_matrix(y_test,y_pred_2))
print("precision Score", precision_score(y_test, y_pred_2))
print("recall Score", recall_score(y_test, y_pred_2))

Accuracy: 0.76
f1 Score 0.43181818181818177
Confusion matrix [[19  5]
 [ 1  0]]
precision Score 0.0
recall Score 0.0

<h4>Decision Tree Model-2 (Temp, Dew Point Temp, Rel Hum, Wind Spd)</h4>
<p> 1. Fit the decision tree model to the dataset(X_train_1,y_train)<p>
<p> 2. Analyzing the best score and the parameter values<p>
<p> 3. Analyzing the predicted output and its probability (X_test_1)<p>
<p> 4. Analyzing the confusion matrix, accuracy scores, precision scores, recall scores and f1 scores <p>

In [517]:
#Fit the decision tree model with X_train and y_train
tree_clf3 = tree_clf3.fit(X_train_1,y_train)

In [518]:
#checking the best score for the model by applying those tuned parameters
#checking the best parameters value for the model after performing hyperparameter tuning
print(tree_clf3.best_score_)
print(tree_clf3.best_params_)

0.8152631578947368
{'criterion': 'gini', 'max_depth': 8, 'min_samples_leaf': 1}

In [519]:
#Applying the tuned parameter values on the Decision tree Model-2 (Temp, Dew Point Temp, Rel Hum, Wind Spd)
#prediction on X_test post hyper parameter tuning
y_pred_3 = tree_clf3.predict(X_test_1)
y_pred_3

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0])

In [520]:
#displaying the probability scores for decision tree Model-2 (Temp, Dew Point Temp, Rel Hum, Wind Spd)
y_pred_proba_3 = tree_clf3.predict_proba(X_test_1)
y_pred_proba_3

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [521]:
#prediction accuracy, precision, recall and f1 scores for model1
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_3))
print("f1 Score", f1_score(y_test, y_pred_3,average = "macro") )
print("Confusion matrix", confusion_matrix(y_test,y_pred_3))
print("precision Score", precision_score(y_test, y_pred_3))
print("recall Score", recall_score(y_test, y_pred_3))

Accuracy: 0.76
f1 Score 0.43181818181818177
Confusion matrix [[19  5]
 [ 1  0]]
precision Score 0.0
recall Score 0.0

<h2> Improving the prediction results by performing under sampling and hyperparameter tuning</h2>

In [522]:
#undersampling for better prediciton results
undersample = NearMiss()
X_train_under, y_train_under = undersample.fit_resample(X_train, y_train)

In [523]:
#input range of values for hyperparameter tuning.
param1 = {"max_depth": range(1,30), "min_samples_leaf": range(1,30), "criterion": ["gini","entropy"]}

In [524]:
# implementation of DecisionTreeClassifier with GridSearchCV
#Fit the decision tree model with X_train and y_train
tree_clf4 = GridSearchCV(clf2, param_grid=param1, cv=5)
tree_clf4 = tree_clf4.fit(X_train_under,y_train_under)

In [525]:
#checking the best score for the model by applying those tuned parameters - after under sampling
#checking the best parameters value for the model after performing hyperparameter tuning - after under sampling
print(tree_clf4.best_score_)
print(tree_clf4.best_params_)

0.75
{'criterion': 'gini', 'max_depth': 1, 'min_samples_leaf': 7}

In [526]:
#Applying the tuned parameter values on the Decision tree Model-1
#prediction on X_test post hyper parameter tuning
y_pred_4 = tree_clf4.predict(X_test)
y_pred_4

array([1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1])

In [527]:
#displaying the probability scores for decision tree Model-2 (Temp, Dew Point Temp, Rel Hum, Wind Spd)
y_pred_proba_4 = tree_clf4.predict_proba(X_test)
y_pred_proba_4

array([[0.125, 0.875],
       [0.125, 0.875],
       [0.8  , 0.2  ],
       [0.125, 0.875],
       [0.8  , 0.2  ],
       [0.125, 0.875],
       [0.8  , 0.2  ],
       [0.125, 0.875],
       [0.8  , 0.2  ],
       [0.125, 0.875],
       [0.125, 0.875],
       [0.125, 0.875],
       [0.125, 0.875],
       [0.125, 0.875],
       [0.8  , 0.2  ],
       [0.125, 0.875],
       [0.125, 0.875],
       [0.8  , 0.2  ],
       [0.125, 0.875],
       [0.125, 0.875],
       [0.125, 0.875],
       [0.125, 0.875],
       [0.125, 0.875],
       [0.125, 0.875],
       [0.125, 0.875]])

In [528]:
#prediction accuracy, precision, recall and f1 scores for model1
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_4))
print("f1 Score", f1_score(y_test, y_pred_4,average = "macro") )
print("Confusion matrix", confusion_matrix(y_test,y_pred_4))
print("precision Score", precision_score(y_test, y_pred_4))
print("recall Score", recall_score(y_test, y_pred_4))

Accuracy: 0.28
f1 Score 0.25
Confusion matrix [[ 6 18]
 [ 0  1]]
precision Score 0.05263157894736842
recall Score 1.0

<h2>Prediction 2020 dataset:</h2>

In [529]:
#Sept 2020 predicable weather data
#read the data for sept 2020 from 5 different stations
#analysing sept 2020 data from one station

#Sep2020
df_2020_sep_DOCKYARD = pd.read_csv('sept-2020/en_climate_hourly_NS_8202240_09-2020_P1H (1).csv', sep=',')
df_2020_sep_STANFIELD_1 = pd.read_csv('sept-2020/en_climate_hourly_NS_8202249_09-2020_P1H.csv', sep=',')
df_2020_sep_STANFIELD_2 = pd.read_csv('sept-2020/en_climate_hourly_NS_8202251_09-2020_P1H.csv', sep=',')
df_2020_sep_KOOTENAY = pd.read_csv('sept-2020/en_climate_hourly_NS_8202252_09-2020_P1H.csv', sep=',')
df_2020_sep_WINDSOR = pd.read_csv('sept-2020/en_climate_hourly_NS_8202255_09-2020_P1H.csv', sep=',')
df_2020_sep_WINDSOR

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time,Year,Month,Day,Time,Temp (Â°C),...,Wind Spd Flag,Visibility (km),Visibility Flag,Stn Press (kPa),Stn Press Flag,Hmdx,Hmdx Flag,Wind Chill,Wind Chill Flag,Weather
0,-63.61,44.66,HALIFAX WINDSOR PARK,8202255,2020-09-01 00:00,2020,9,1,00:00,13.6,...,NaN,NaN,NaN,101.53,NaN,NaN,NaN,NaN,NaN,NaN
1,-63.61,44.66,HALIFAX WINDSOR PARK,8202255,2020-09-01 01:00,2020,9,1,01:00,13.4,...,NaN,NaN,NaN,101.55,NaN,NaN,NaN,NaN,NaN,NaN
2,-63.61,44.66,HALIFAX WINDSOR PARK,8202255,2020-09-01 02:00,2020,9,1,02:00,12.4,...,NaN,NaN,NaN,101.58,NaN,NaN,NaN,NaN,NaN,NaN
3,-63.61,44.66,HALIFAX WINDSOR PARK,8202255,2020-09-01 03:00,2020,9,1,03:00,11.4,...,NaN,NaN,NaN,101.63,NaN,NaN,NaN,NaN,NaN,NaN
4,-63.61,44.66,HALIFAX WINDSOR PARK,8202255,2020-09-01 04:00,2020,9,1,04:00,10.2,...,NaN,NaN,NaN,101.65,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,-63.61,44.66,HALIFAX WINDSOR PARK,8202255,2020-09-30 19:00,2020,9,30,19:00,19.4,...,NaN,NaN,NaN,100.01,NaN,NaN,NaN,NaN,NaN,NaN
716,-63.61,44.66,HALIFAX WINDSOR PARK,8202255,2020-09-30 20:00,2020,9,30,20:00,18.8,...,NaN,NaN,NaN,100.10,NaN,NaN,NaN,NaN,NaN,NaN
717,-63.61,44.66,HALIFAX WINDSOR PARK,8202255,2020-09-30 21:00,2020,9,30,21:00,17.7,...,NaN,NaN,NaN,100.23,NaN,NaN,NaN,NaN,NaN,NaN
718,-63.61,44.66,HALIFAX WINDSOR PARK,8202255,2020-09-30 22:00,2020,9,30,22:00,17.0,...,NaN,NaN,NaN,100.28,NaN,NaN,NaN,NaN,NaN,NaN
719,-63.61,44.66,HALIFAX WINDSOR PARK,8202255,2020-09-30 23:00,2020,9,30,23:00,16.4,...,NaN,NaN,NaN,100.37,NaN,NaN,NaN,NaN,NaN,NaN

In [530]:
#preprocessing reusable function1
#analysing sept 2020 data from one station after applying preprocessing function1

#2020
df_2020_sep_DOCKYARD  = preProcessing(df_2020_sep_DOCKYARD)
df_2020_sep_STANFIELD_1  = preProcessing(df_2020_sep_STANFIELD_1)
df_2020_sep_STANFIELD_2  = preProcessing(df_2020_sep_STANFIELD_2)
df_2020_sep_KOOTENAY  = preProcessing(df_2020_sep_KOOTENAY)
df_2020_sep_WINDSOR  = preProcessing(df_2020_sep_WINDSOR)
df_2020_sep_WINDSOR

,Date/Time,Year,Month,Day,Time,Temp (Â°C),Dew Point Temp (Â°C),Rel Hum (%),Wind Spd (km/h)
Date/Time,,,,,,,,,
2020-09-01 00:00:00,2020-09-01 00:00,2020,9,1,00:00,13.6,7.1,65.0,8.0
2020-09-01 01:00:00,2020-09-01 01:00,2020,9,1,01:00,13.4,6.9,65.0,9.0
2020-09-01 02:00:00,2020-09-01 02:00,2020,9,1,02:00,12.4,7.6,72.0,8.0
2020-09-01 03:00:00,2020-09-01 03:00,2020,9,1,03:00,11.4,7.9,79.0,3.0
2020-09-01 04:00:00,2020-09-01 04:00,2020,9,1,04:00,10.2,8.9,91.0,0.0
...,...,...,...,...,...,...,...,...,...
2020-09-30 19:00:00,2020-09-30 19:00,2020,9,30,19:00,19.4,19.4,100.0,24.0
2020-09-30 20:00:00,2020-09-30 20:00,2020,9,30,20:00,18.8,18.7,100.0,23.0
2020-09-30 21:00:00,2020-09-30 21:00,2020,9,30,21:00,17.7,17.7,100.0,14.0
2020-09-30 22:00:00,2020-09-30 22:00,2020,9,30,22:00,17.0,16.9,100.0,12.0
2020-09-30 23:00:00,2020-09-30 23:00,2020,9,30,23:00,16.4,16.4,100.0,11.0

In [531]:
#Concatenating the tables by different stations by means of values for 2020 predicable weather data for september
#because 'Date/Time' is an unique autoincremental value and all the table have the same ''Date/Time''. therefore, we can use it from any
#any table of groupby
df_2020_test_sep = pd.concat([df_2020_sep_DOCKYARD, df_2020_sep_STANFIELD_1, df_2020_sep_STANFIELD_2, df_2020_sep_KOOTENAY, df_2020_sep_WINDSOR]).groupby(df_2020_sep_STANFIELD_1['Date/Time']).mean()

In [532]:
#Preprocessing reusable function 2
#analysing sept 2020 data from all station after applying preprocessing function2
df_2020_test_datasets = preProcessing2(df_2020_test_sep)
df_2020_test_datasets

     Year  Month  Temp (Â°C)  Dew Point Temp (Â°C)  Rel Hum (%)  Wind Spd (km/h)
Day
1    2020      9  14.834167             8.846667    69.616667         7.033333
2    2020      9  14.353151            12.335956    88.897689        11.454097
3    2020      9  18.636823            18.385915    98.542904        15.505509
4    2020      9  20.286667            19.057500    93.258333        12.933333
5    2020      9  18.948333            11.846667    66.675000        10.733333
6    2020      9  16.999682             9.933763    65.506221         9.057428
7    2020      9  15.844167            13.971667    90.341667         9.050000
8    2020      9  19.642500            17.256667    88.316667         7.608333
9    2020      9  18.826667            17.010833    90.891667         5.316667
10   2020      9  20.482500            20.293333    98.875000         8.108333
11   2020      9  14.911667            12.584167    86.791667        15.291667
12   2020      9  13.548333             8.218333    72.900000         6.916667
13   2020      9  15.440833            12.273333    82.383333        11.491667
14   2020      9  18.391349            15.292929    83.681221        12.482428
15   2020      9  11.917500             5.459167    65.491667        12.733333
16   2020      9  13.045833             7.166667    69.575000        14.283333
17   2020      9  17.868333            14.498333    81.358333        18.266667
18   2020      9  13.602500            12.694167    94.416667        10.391667
19   2020      9  11.235000             3.472500    60.533333        15.691667
20   2020      9   9.348333             2.330833    64.741667        11.258333
21   2020      9   9.849167             4.255000    71.441667         9.583333
22   2020      9   9.689167             8.308333    91.641667        19.791667
23   2020      9  13.997192            12.619206    91.810685        22.617260
24   2020      9  16.548333            11.609167    74.283333        14.316667
25   2020      9  14.034167             8.588333    72.691667         8.458333
26   2020      9  13.613333            10.422500    82.958333         9.925000
27   2020      9  17.370833            16.581667    95.625000        13.525000
28   2020      9  19.044167            18.797500    98.541667        15.458333
29   2020      9  20.345000            19.644167    96.033333        15.808333
30   2020      9  19.062500            19.000000    99.616667        20.833333

In [533]:
#combining two dataframes to make the final prediction dataset
#drop Month and year from final prediction dataset
#checking the sample records of the final prediction dataset
final_test_dataset = pd.concat([workout_work_dataset_test, df_2020_test_datasets], axis=1, sort=False)
final_test_dataset = final_test_dataset.drop(['Month','Year'], axis=1)
final_test_dataset.head(10)

,Exercise,Working,Temp (Â°C),Dew Point Temp (Â°C),Rel Hum (%),Wind Spd (km/h)
1,0,1,14.834167,8.846667,69.616667,7.033333
2,1,1,14.353151,12.335956,88.897689,11.454097
3,0,1,18.636823,18.385915,98.542904,15.505509
4,1,1,20.286667,19.057500,93.258333,12.933333
5,0,1,18.948333,11.846667,66.675000,10.733333
6,1,1,16.999682,9.933763,65.506221,9.057428
7,0,0,15.844167,13.971667,90.341667,9.050000
8,0,0,19.642500,17.256667,88.316667,7.608333
9,0,1,18.826667,17.010833,90.891667,5.316667
10,0,1,20.482500,20.293333,98.875000,8.108333

In [534]:
# Rearranging columns to put dependent variable at last
final_test_dataset = final_test_dataset[[
 'Temp (Â°C)',
 'Dew Point Temp (Â°C)',
 'Rel Hum (%)',
 'Wind Spd (km/h)',
 'Working',
 'Exercise']]

In [535]:
#Standardization of features - final prediction dataset
#checking the final prediciton dataset after data preprocessing and standardization
final_test_dataset.iloc[:, :4] = sc.transform(final_test_dataset.iloc[:, :4])
final_test_dataset

,Temp (Â°C),Dew Point Temp (Â°C),Rel Hum (%),Wind Spd (km/h),Working,Exercise
1,1.190345,0.837840,-0.896726,-1.395063,1,0
2,1.118909,1.339690,1.098320,-0.716131,1,1
3,1.755081,2.209831,2.096329,-0.093923,1,0
4,2.000101,2.306422,1.549524,-0.488953,1,1
5,1.801344,1.269317,-1.201107,-0.826824,1,0
6,1.511948,0.994192,-1.322042,-1.084206,1,1
7,1.340341,1.574947,1.247731,-1.085347,0,0
8,1.904435,2.047415,1.038200,-1.306755,0,0
9,1.783275,2.012058,1.304641,-1.658705,1,0
10,2.029184,2.484167,2.130692,-1.229966,1,0
11,1.201855,1.375389,0.880405,-0.126765,1,0
12,0.999385,0.747469,-0.556993,-1.412980,1,0
13,1.280442,1.330683,0.424266,-0.710361,1,0
14,1.718626,1.764979,0.558561,-0.558202,1,0
15,0.757189,0.350629,-1.323548,-0.519668,0,0
16,0.924758,0.596212,-0.901038,-0.281622,0,0
17,1.640952,1.650696,0.318207,0.330130,1,0
18,1.007429,1.391210,1.669379,-0.879297,1,0
19,0.655830,0.064895,-1.836597,-0.065334,1,0
20,0.375639,-0.099306,-1.401152,-0.746196,1,0
21,0.450019,0.177439,-0.707890,-1.003439,1,0
22,0.426257,0.760413,1.382245,0.564336,1,0
23,1.066045,1.380428,1.399733,0.998285,0,0
24,1.444918,1.235159,-0.413857,-0.276503,0,0
25,1.071537,0.800684,-0.578550,-1.176214,1,0
26,1.009038,1.064485,0.483763,-0.950966,1,0
27,1.567068,1.950333,1.794408,-0.398086,1,1
28,1.815576,2.269027,2.096201,-0.101168,1,0
29,2.008764,2.390800,1.836659,-0.047416,1,0
30,1.818299,2.298152,2.207434,0.724313,1,0

In [539]:
#applying the prediction dataset on the trained decision tree models
y_pred_final_1 = tree_clf.predict(final_test_dataset)
y_pred_final_2 = tree_clf2.predict(final_test_dataset)
y_pred_final_3 = tree_clf4.predict(final_test_dataset)

In [541]:
#displaying the prediction values after running the models against the dataset
print("Baseline Model:",y_pred_final_1)
print("Model after hyperparameter tuning:",y_pred_final_2)
print("Model after under sampling and hyperparameter tuning:",y_pred_final_3)

Baseline Model: [0 0 1 1 1 0 0 1 1 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 1 1 1]
Model after hyperparameter tuning: [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
Model after under sampling and hyperparameter tuning: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0]

In [542]:
#checking the prediction probability result - model after hyper parameter tuning with final prediction dataset
y_pred_proba_final_1 = tree_clf.predict_proba(final_test_dataset)
y_pred_proba_final_2 = tree_clf2.predict_proba(final_test_dataset)
y_pred_proba_final_3 = tree_clf4.predict_proba(final_test_dataset)

In [543]:
#displaying the probability scores after running the models against the dataset
print("Baseline Model:",y_pred_proba_final_1)
print("Model after hyperparameter tuning:",y_pred_proba_final_2)
print("Model after under sampling and hyperparameter tuning:",y_pred_proba_final_3)

Baseline Model: [[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]
Model after hyperparameter tuning: [[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]
Model after under sampling and hyperparameter tuning: [[0.8   0.2  ]
 [0.8   0.2  ]
 [0.8   0.2  ]
 [0.8   0.2  ]
 [0.8   0.2  ]
 [0.8   0.2  ]
 [0.8   0.2  ]
 [0.8   0.2  ]
 [0.8   0.2  ]
 [0.8   0.2  ]
 [0.8   0.2  ]
 [0.8   0.2  ]
 [0.8   0.2  ]
 [0.8   0.2  ]
 [0.125 0.875]
 [0.125 0.875]
 [0.8   0.2  ]
 [0.8   0.2  ]
 [0.125 0.875]
 [0.125 0.875]
 [0.125 0.875]
 [0.125 0.875]
 [0.8   0.2  ]
 [0.8   0.2  ]
 [0.8   0.2  ]
 [0.8   0.2  ]
 [0.8   0.2  ]
 [0.8   0.2  ]
 [0.8   0.2  ]
 [0.8   0.2  ]]